version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
     - 5432:5432
    restart: always
    environment: 
      - POSTGRES_DB={DB_DATABASE}
      - POSTGRES_USER={DB_USERNAME}
      - POSTGRES_PASSWORD={DB_PASSWORD}